
export const BaseTeams = [
    {
        "name": "FC Köln",
        "shortName": "FC Köln",
        "tla": "KOE",
        "crestUrl": "https://crests.football-data.org/1.svg",
        "clubColors": "Red / White",
        "venue": "RheinEnergieSTADION",
    },
    {
        "name": "TSG 1899 Hoffenheim",
        "shortName": "Hoffenheim",
        "tla": "TSG",
        "crestUrl": "https://crests.football-data.org/2.svg",
        "clubColors": "Blue / White",
        "venue": "PreZero Arena",
    },
    {
        "name": "Bayer 04 Leverkusen",
        "shortName": "Leverkusen",
        "tla": "B04",
        "crestUrl": "https://crests.football-data.org/3.svg",
        "clubColors": "Red / White / Black",
        "venue": "BayArena",
    },
    {
        "name": "Borussia Dortmund",
        "shortName": "Dortmund",
        "tla": "BVB",
        "crestUrl": "https://crests.football-data.org/4.svg",
        "clubColors": "Black / Yellow",
        "venue": "Signal Iduna Park",
    },
    {
        "name": "FC Bayern München",
        "shortName": "Bayern",
        "tla": "FCB",
        "crestUrl": "https://crests.football-data.org/5.svg",
        "clubColors": "Red / White / Blue",
        "venue": "Allianz Arena",
    },
    {
        "name": "Hertha BSC",
        "shortName": "Hertha BSC",
        "tla": "BSC",
        "crestUrl": "https://crests.football-data.org/9.svg",
        "clubColors": "Blue / White",
        "venue": "Olympiastadion Berlin",
    },
    {
        "name": "VfB Stuttgart",
        "shortName": "Stuttgart",
        "tla": "VFB",
        "crestUrl": "https://crests.football-data.org/10.svg",
        "clubColors": "White / Red",
        "venue": "Mercedes-Benz Arena",
    },
    {
        "name": "VfL Wolfsburg",
        "shortName": "Wolfsburg",
        "tla": "WOB",
        "crestUrl": "https://crests.football-data.org/11.svg",
        "clubColors": "Green / White",
        "venue": "Volkswagen Arena",
    },
    {
        "name": "FSV Mainz 05",
        "shortName": "Mainz",
        "tla": "M05",
        "crestUrl": "https://crests.football-data.org/15.svg",
        "clubColors": "Red / White",
        "venue": "Opel Arena",
    },
    {
        "name": "FC Augsburg",
        "shortName": "Augsburg",
        "tla": "FCA",
        "crestUrl": "https://crests.football-data.org/16.svg",
        "clubColors": "Red / Green / White",
        "venue": "WWK Arena",
    },
    {
        "name": "SC Freiburg",
        "shortName": "Freiburg",
        "tla": "SCF",
        "crestUrl": "https://crests.football-data.org/17.svg",
        "clubColors": "Red / White",
        "venue": "Schwarzwald-Stadion",
    },
    {
        "name": "Borussia Mönchengladbach",
        "shortName": "M'gladbach",
        "tla": "BMG",
        "crestUrl": "https://crests.football-data.org/18.svg",
        "clubColors": "Black / White / Green",
        "venue": "Stadion im Borussia-Park",
    },
    {
        "name": "Eintracht Frankfurt",
        "shortName": "Frankfurt",
        "tla": "SGE",
        "crestUrl": "https://crests.football-data.org/19.svg",
        "clubColors": "Red / Black",
        "venue": "Deutsche Bank Park",
    },
    {
        "name": "SpVgg Greuther Fürth 1903",
        "shortName": "Greuther Fürth",
        "tla": "FUR",
        "crestUrl": "https://crests.football-data.org/21.svg",
        "venue": "Sportpark Ronhof Thomas Sommer",
    },
    {
        "name": "1. FC Union Berlin",
        "shortName": "Union Berlin",
        "tla": "UNB",
        "crestUrl": "https://crests.football-data.org/28.svg",
        "clubColors": "Red / White",
        "venue": "Stadion An der Alten Försterei",
    },
    {
        "name": "VfL Bochum 1848",
        "shortName": "Bochum",
        "tla": "BOC",
        "crestUrl": "https://crests.football-data.org/36.svg",
        "clubColors": "Blue / White",
        "venue": "Vonovia Ruhrstadion",
    },
    {
        "name": "Arminia Bielefeld",
        "shortName": "Bielefeld",
        "tla": "BIE",
        "crestUrl": "https://crests.football-data.org/38.svg",
        "clubColors": "Black / White / Blue",
        "venue": "SchücoArena Kunstrasenplatz",
    },
    {
        "name": "RB Leipzig",
        "shortName": "RB Leipzig",
        "tla": "RBL",
        "crestUrl": "https://crests.football-data.org/721.svg",
        "clubColors": "White / Red",
        "venue": "Red Bull Arena",
    }
];